modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[dependencies.village_flag]]
    modId="forge"
    mandatory=true
    versionRange="[47.3.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.village_flag]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
A land claim system tied to villages. Flags protect areas by switching non-owners to adventure mode.
'''
